version: "3"

services:
  frontend:
    image: react-ui:latest
    container_name: react-ui
    # restart: always
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - mern-networks
    volumes:
      - ./frontend:/app

  backend:
    image: node-api:latest
    container_name: node-api
    # restart: always
    ports:
      - "5000:5000"
    depends_on:
      - database
    networks:
      - mern-networks
    volumes:
      - ./backend:/app
    env_file: ./backend/config/${ENV}.env

  
  database:
    image: mongo:4.4-bionic
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpwd
      - MONGO_INITDB_DATABASE=my_db
    container_name: mongo-db
    # restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./docker-entrypoint-initdb.d/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - mern-networks

  
networks:
  mern-networks:
    driver: bridge

volumes:
  mongo-data:
    driver: local