version: "3"

services:
  frontend:
    image: react-ui-production
    container_name: react-ui
    restart: unless-stopped
    ports:
      - "3000:80"
    stdin_open: true
    depends_on:
      - backend
    networks:
      - mern-networks

  backend:
    image: node-api
    container_name: node-api
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - database
    env_file: ./backend/config/${ENV}.env
    networks:
      - mern-networks
  
  database:
    image: mongo:4.4-bionic
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpwd
      - MONGO_INITDB_DATABASE=my_db
    container_name: mongo-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./docker-entrypoint-initdb.d/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - mern-networks

networks:
  mern-networks:
    driver: bridge

volumes:
  mongo-data:
    driver: local